spring.application.name=salessaive


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

razorpay.key_id=${RAZORPAY_KEY}
razorpay.key_secret=${RAZORPAY_SECRET}

openai.api.key=${OPENAI_API_KEY}